---

- name: install default packets
  yum: name={{ item }} state=present
  with_items:
    - vim
    - net-tools
    - bash-completion
    - wget 
    - curl 
    - lsof
    - nano
    - iptables-services
    - fail2ban