---

- name: sudoers config
  template: src=sudoers.j2 dest=/etc/sudoers

- name: sshd config
  template: src=sshd.j2 dest=/etc/ssh/sshd_config
  notify: restart sshd
  
- name: Set SELinux in permissive mode until the machine is rebooted
  shell: setenforce 0
  ignore_errors: True

- name: Default Firewall
  command: "{{item}}"
  with_items:
    - 'iptables -F'
    - 'iptables -P OUTPUT ACCEPT'
    - 'iptables -P FORWARD DROP'
    - 'iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'
    - 'iptables -A INPUT -p icmp -j ACCEPT'
    - 'iptables -A INPUT -i lo -j ACCEPT'
    - 'iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 1965 -j ACCEPT'
    - 'iptables -N SCANNER'
    - 'iptables -A SCANNER -m limit --limit 15/m -j LOG --log-level 6 --log-prefix "FW: port scanner:"'
    - 'iptables -A SCANNER -j DROP'
    - 'iptables -A INPUT -p tcp --tcp-flags ALL FIN,URG,PSH -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags ALL NONE -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags ALL ALL -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags ALL FIN,SYN -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -i eth1 -j SCANNER'
    - 'iptables -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -i eth1 -j SCANNER'
    - 'iptables -P INPUT DROP'
    - 'service iptables save'
    - 'systemctl enable iptables'
    - 'systemctl start iptables'